name: Deploy to GCP Cloud Run

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker to use gcloud as credential helper
      run: gcloud auth configure-docker

    - name: Build and deploy using Cloud Build
      run: |
        gcloud builds submit --config cloudbuild.yaml .

    - name: Get service URL
      run: |
        SERVICE_URL=$(gcloud run services describe runon-service \
          --region=asia-northeast3 \
          --format="value(status.url)")
        echo "Service deployed at: $SERVICE_URL"