name: Deploy to GCP Cloud Run

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker to use gcloud as credential helper
      run: gcloud auth configure-docker

    - name: Build and deploy using Cloud Build
      run: |
        gcloud builds submit --config cloudbuild.yaml --project=${{ secrets.GCP_PROJECT_ID }} .

    - name: Get service URL
      run: |
        SERVICE_URL=$(gcloud run services describe runon-service \
          --region=asia-northeast3 \
          --project=${{ secrets.GCP_PROJECT_ID }} \
          --format="value(status.url)")
        echo "Service deployed at: $SERVICE_URL"